### ISSUE TITLE
Please release a new version to fix GHC compiler crashes while building the test suite

### ISSUE THREAD

**Issue by peti** [GaloisInc/SHA#14]
Please release a new version that includes c258350e953c3de2f98c5625ac3857f1a6863afc. We are seeing compiler crashes trying to build `SHA` in Nixpkgs that could be avoided if that fix were available from Hackage.

**Comment by mpickering** [comment]
It seems thee fix wasn’t applied to the executables for the package.

**Comment by acw** [comment]
1.6.4.4 should do the trick. Tell me if you have any problems!

**Comment by peti** [comment]
Thank you very much for the quick response!
